### ISSUE TITLE
Unable to remove Dashboard and Settings links

### ISSUE THREAD

**Issue by alexagui** [wbrowar/craft-admin-bar#10]
I've been trying to remove the Dashboard and Setting links.

But despite creating a `craft/config/adminbar.php`file and updating with:

```
    'displayDashboardLink' => false,
    'displayDefaultEditSection' => false,
```

It still shows those buttons on the front-end.

**Comment by wbrowar** [comment]
Hi, Alex. I'll take a look this weekend. The Settings link has been on my radar since project config, but I haven't had a chance to get to it. Thanks!

**Comment by wbrowar** [comment]
@alexagui Hey Alex, regarding your settings, I changed the handle of the plugin to `admin-bar` when re-building it for Craft 3. If your config file is changed to `admin-bar.php` then those settings should now work.

There was a bug with `displayDefaultEditSection` and that's now all set. Thanks for letting me know!

**Comment by alexagui** [comment]
Thanks Will!
