### ISSUE TITLE
[FR] Hide Dashboard link if Dashboard Begone is installed

### ISSUE THREAD

**Issue by darylknight** [wbrowar/craft-admin-bar#19]
Thanks for your work on this! We just transitioned a client from WordPress to Craft and the first thing they asked was "Is there a bar at the top of the front end we can use to go directly to edit a page?" - Admin Bar to the rescue.

This is probably out of scope, but just thought I'd note the first thing I saw on installing this; I typically install [Dashboard Begone](https://github.com/putyourlightson/craft-dashboard-begone) on every site, but there's a link to the Dashboard in Admin bar on the front end. It would be good to be able to either detect this automatically, or add a toggle switch to hide it.

**Comment by wbrowar** [comment]
Hey @darylknight, there's actually a config option for this: `displayDashboardLink`

If you create a config file at `config/admin-bar.php` you can set that to `false` and the Dashboard link should disappear.

You can take a look at this config file for other available options: https://github.com/wbrowar/craft-adminbar/blob/master/src/config.php

**Comment by darylknight** [comment]
Brilliant, thank you!
