### ISSUE TITLE
[FR] Customisable section names

### ISSUE THREAD

**Issue by darylknight** [wbrowar/craft-admin-bar#20]
I tend to name my sections in plural, things like Pages, Events, Materials etc. as that makes sense when looking at the Entries section in the control panel.

I notice that on the front end, Admin Bar edit links use the section titles in these plural terms which doesn't make a lot of sense when you're expecting to "edit page". Could we have the ability to either rename the sections for Admin Bar, or maybe change it to something like "Edit Entry" rather than "Edit [section name]"?

**Comment by wbrowar** [comment]
Hey @darylknight, there is a way to turn off the section name, by setting `displayDefaultEditSection` to false. In that case it would just say `EDIT` without any section name.

I'm also not opposed to letting the entire label be changed, though. I'll work on that for a future update.

**Comment by darylknight** [comment]
That solves it, thank you! Feel free to close, or leave open if you want to add editable label names 🙂
