### ISSUE TITLE
Better responsive Layout

### ISSUE THREAD

**Issue by MichaelBrauner** [wbrowar/craft-admin-bar#21]
I generally like this plugin a lot - coming from drupal I kinda need it :). 

But it looks awful on mobile devices. 

What can I do, to fix it? Can I help?

**Comment by wbrowar** [comment]
Hey, @Slowwie, I’m going to be updating the build system and including it in this repo so it’ll be easier to contribute going forward. I’d _love_ some suggestions and, even better, PRs after I move the Webpack build over. I’ll post another comment here when I get to it, but it might be a few weeks before I can find the time to set it all up.

Thanks for offering to pitch in 😃

**Comment by darylknight** [comment]
Did this move forward any further? I just came to file a bug report about the mobile view. Looks fine when you first get there:

![image](https://user-images.githubusercontent.com/1250017/129008563-bb2917d5-313e-43f6-9877-5dcf1007a1b6.png)

But when you click the edit button, you get this:

![image](https://user-images.githubusercontent.com/1250017/129008593-549b5e14-889e-40f1-9532-0e3c39def7cf.png)

**Comment by wbrowar** [comment]
Hey, everyone. With the new setup using the [Admin Bar Component](https://github.com/wbrowar/admin-bar-component), I ditched the mobile layout for now, in favor of letting you horizontally scroll through the buttons. I'd like to come back to working on a mobile layout again, but I'd like to make it a little more solid and maybe look at a more modern approach to the UI.

I'm going to close this for now and will continue to work on a solution in the Admin Bar Component repo instead.
