### ISSUE TITLE
Does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by ghost** [wbrowar/craft-admin-bar#22]
Hi teams,

The composer output the following notice at every time I run `composer update`.
`Deprecation Notice: Class wbrowar\adminbar\assetbundles\AdminBar\AdminBarAsset located in ./vendor/wbrowar/adminbar/src/assetbundles/adminbar/AdminBarAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201`
Can you fix it?

Thanks,

**Comment by wbrowar** [comment]
Thanks, @dande-sun! I’ll have this fixed in 3.1.11
