### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [wbrowar/craft-admin-bar#23]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `wbrowar\adminbar\assetbundles\AdminBar\AdminBarAsset` located in `./vendor/wbrowar/adminbar/src/assetbundles/adminbar/AdminBarAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/adminbar src/assetbundles/AdminBar
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by wbrowar** [comment]
Thanks, Brandon! This is all set in 3.1.11

**Comment by brandonkelly** [comment]
Thanks!
