### ISSUE TITLE
Not loading CSS or JS assets in production environment

### ISSUE THREAD

**Issue by GaryReckard** [wbrowar/craft-admin-bar#27]
I am implementing the AdminBar using the javascript method. I have `{{ getAdminBarAssets({ uri: craft.app.request.url }) }}` just after the opening <body> tag in my layout twig file, and the necessary javascript functions to fetch the adminbar html. 

Everything works fine in my local and staging environments, but when I deploy this to my production environment, and log in as an admin to test it out, it seems the CSS and JS assets do not get loaded. 

It looks like `getAdminBarAssets` is outputting something, just empty:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1679951/165777599-7bb9fbe5-d4b4-41a0-968e-aee8d73e94c7.png">

I see the HTML content unstyled, like so:

<img width="101" alt="image" src="https://user-images.githubusercontent.com/1679951/165776714-d9401944-2e7f-4d3e-9ffa-45df8b7f2da5.png">

Any idea what could cause this, and how to fix? Thanks!

Craft: v3.7.27.2
AdminBar: 3.1.11

**Comment by wbrowar** [comment]
Hi, @GaryReckard, I’ll take a look and see if I can reproduce this on my end. Just to rule it out, do you have any sort of caching on production that might have cached the CSS in the empty state?
