### ISSUE TITLE
Request for Craft 4 compatibility

### ISSUE THREAD

**Issue by darylknight** [wbrowar/craft-admin-bar#28]
Please update to be compatible with Craft 4 :)

![image](https://user-images.githubusercontent.com/1250017/166912585-45cf2f0e-56b5-4257-b1a4-779504db7ed2.png)

**Comment by darylknight** [comment]
Answered on Discord: https://discord.com/channels/456442477667418113/456442477667418115/971737963815903242. Feel free to close this, or leave here in case other people come searching for Craft 4 updates too :)

**Comment by wbrowar** [comment]
Hey @darylknight, please take a look at the compatibility branch when you have a chance. You can test it out on a Craft 4 site by setting this version in your composer file:
```
"wbrowar/adminbar": "dev-3.x-craft-4"
```

I've given it a good testing, but if you have a very complicated setup then you may run into edge cases. If you run into any issues, please leave another comment here and I'll take a look. I'm hoping to have a release out by the end of the weekend.

**Comment by darylknight** [comment]
Thanks for this! I'm not sure how other devs are handling this, but the first problem I run into is that the dev release requires Craft 4 to install. If you're still on Craft 3.x (which I am at the moment) it wouldn't be possible to install this in order to upgrade to Craft 4, and it's showing as "Not Ready" on the upgrade tool

![image](https://user-images.githubusercontent.com/1250017/167241560-d36e00b7-0700-4cb0-a38f-0165f0756af9.png)

![image](https://user-images.githubusercontent.com/1250017/167241554-113d5778-f4cb-40f3-a031-71c4e274fad6.png)

**Comment by darylknight** [comment]
@wbrowar This appears to be working perfectly for me in Craft 4, thank you!
