### ISSUE TITLE
Custom CSS is not saved

### ISSUE THREAD

**Issue by darylknight** [wbrowar/craft-admin-bar#29]
I need the admin bar to appear at the bottom of the site I'm working on, so I just went and added this under settings:

![image](https://user-images.githubusercontent.com/1250017/200584798-edf3c818-0da1-485e-a589-e389c535b49d.png)

However - when I save the page, it does not save the CSS, and when I go back, the Custom CSS field is blank again.

Admin Bar 3.2.0
Craft CMS 4.3.1

**Comment by darylknight** [comment]
Ah, just worked this out - I had this in my config file:

![image](https://user-images.githubusercontent.com/1250017/200585436-63a85499-9d08-415e-a5ed-50f201ae5132.png)

It's not really explained anywhere, but this is what gets loaded into the Custom CSS field, even if you save something into it using the control panel. Now that I've commented out that line in the config file, it correctly loads the CSS from Project Config

**Comment by wbrowar** [comment]
Okay, for the 4.0 release I removed the `customCss` key from the `config.php` file so going forward copying and renaming that file won't result in this happening again.
