### ISSUE TITLE
Wrong config file path documented

### ISSUE THREAD

**Issue by mtnorthrop** [wbrowar/craft-admin-bar#30]
In `src/config.php`,  it says:

https://github.com/wbrowar/craft-adminbar/blob/158c738d4138ec6e202e28eebc34e6f732e9c386/src/config.php#L17-L18

When you're on Craft 4, the config file should actually be copied to `config` and named `admin-bar.php`.

**Comment by wbrowar** [comment]
Thanks for catching this. I had changed the plugin handle at one point and missed this in the documentation. I'm currently going through and cleaning up all broken and missing doc blocks for the 4.0 release. I'll make sure this is updated with it.
