### ISSUE TITLE
Doesn't seem to work with Craft 3.0.0-beta.22

### ISSUE THREAD

**Issue by cholawo** [wbrowar/craft-admin-bar#4]
Hi, when I update to Craft cms 3.0.0-beta.22 I get an error message 
`Internal Server Error Unable to locate message source for category 'adminbar'.`
I've tried removing and re-adding the adminbar plugin but to no avail.

**Comment by wbrowar** [comment]
Thanks, Matt. Sorry it's taking so long to get back to this, but I'll be working on this and a few other changes over the next couple of weeks..

**Comment by wbrowar** [comment]
Yeah... Sorry again, Matt. Thanks to some help by @MakeilaLundy I was able to fix the compatibility issues and got Admin Bar working again. Thanks for your patience.
