### ISSUE TITLE
Request for Craft 4 compatibility

### ISSUE THREAD

**Issue by JaneConvergine** [wbrowar/craft-admin-bar#41]
Could you please let us know when Craft 5 version will be released?

**Comment by wbrowar** [comment]
Hi @JaneConvergine, I'm working on updating all of my plugins now. I hope to have a beta release for Admin Bar within the next week or so, then will plan on tagging the full release when Craft 5.0 is officially released. I'll share updates on this issues as things change.

**Comment by wbrowar** [comment]
@JaneConvergine, I made the main updates to get Admin Bar working in Craft 5. If you want to test out these changes you can set your composer version to:
```
"wbrowar/craft-admin-bar": "dev-main"
```

I'll be doing some more testing on it. If you give it a try and you run into any issues with the new version, please leave me another issue and I'll be sure to take a look.

**Comment by wbrowar** [comment]
Hi, @JaneConvergine, there is a beta release of Admin Bar up on the Craft 5 Plugin Store. Please go ahead and update and let me know if you run into any issues along the way. I'm going to test this out on some of my own Craft projects and then if all goes well get a final release up in a week or so.

Here's the link if you want to take a look:
https://plugins.craftcms.com/admin-bar?craft5

**Comment by wbrowar** [comment]
@JaneConvergine, I've been testing Admin Bar and just tagged the 5.0.0 release! Please let me know if you run into any issues, but I think it's pretty solid at the moment.
