### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by NeleDeBruycker** [wbrowar/craft-admin-bar#42]
Hi, 

We noticed that the admin bar is missing a background color. After some digging in the devtools we noticed that there is an issue with the linear-gradient. 
<img width="1792" alt="image" src="https://github.com/wbrowar/craft-admin-bar/assets/69677343/2a1cc191-783d-400e-989f-88cb7c46e82a">

There is a space missing in "tobottom". When adding a space "to bottom", the background gradient appeared. 
![image](https://github.com/wbrowar/craft-admin-bar/assets/69677343/24769b85-863e-438f-bfb1-710e11e2d648)

Besides that, the hover states are not that accessible as the background is turning white but the highlight color is not showing correctly. This because the OKLCH colors are missing properties. (It requires a L, C and H parameter)
<img width="362" alt="image" src="https://github.com/wbrowar/craft-admin-bar/assets/69677343/406396af-89b9-4942-b5d7-e22f9ef30499">

**Comment by wbrowar** [comment]
@NeleDeBruycker, good catch and thanks for letting me know! I'll fix this for the next release.

**Comment by wbrowar** [comment]
Hi @NeleDeBruycker,

I've tried to re-create this issue and I'm not seeing it happen with Admin Bar’s default behavior. I've double-checked Admin Bar and [admin-bar-component](https://www.npmjs.com/package/admin-bar-component) and didn't see an issue with the CSS output.

Is there any chance you are using some sort of minification tool on your templates (such as the [Minify](https://plugins.craftcms.com/minify) plugin)? Looking at your screenshot it looks like all spaces are getting stripped out in the values being set and that would mean a bunch of values aren't getting set properly.

**Comment by wbrowar** [comment]
Ah, right when I posted that last comment I gave it another run through the asset build and I see some funky behavior in its minification. I'm going to turn it off as it only saves a few bytes in this situation.

**Comment by wbrowar** [comment]
@NeleDeBruycker, I just tagged a release for v5 and it includes this change. Please let me know if you run into any other issues with it. Thanks again for making this issue!
