### ISSUE TITLE
Taking into account users permissions for editing entries

### ISSUE THREAD

**Issue by Djive** [wbrowar/craft-admin-bar#8]
Feature request

Is it possible to have the "edit entry" button hidden if the user doesn't have permission to edit that entry?

At the moment all users see the button always, even though they don't have permission to edit the entry and clicking on that button leads to error page with following error:

HTTP 403 – Forbidden – yii\web\ForbiddenHttpException
User is not permitted to perform this action

Thanks!

**Comment by wbrowar** [comment]
@Djive Thanks for the suggestion! I can't believe I hadn't thought of that in the entire time Admin Bar's been around 😂

I'm a little swamped with client work and other things, but I'll add this check and your other suggestions (thanks for those on Content Stats, too) when I have a chance.

**Comment by wbrowar** [comment]
@Djive This is all set in 3.1.7. Thanks again for the idea!
