### ISSUE TITLE
ReflectionException - AdminBarAsset does not exist

### ISSUE THREAD

**Issue by nickcobley** [wbrowar/craft-admin-bar#9]
Running AdminBar 3.1.6 on Craft 3.1.8 I get this error whenever I try to access the settings area of Craft, not the settings of Admin Bar, just Craft CP itself.

I think this started with the upgrade to Craft 3.1 but I can't be absolutely sure.

```
ReflectionException
Class wbrowar\adminbar\assetbundles\AdminBar\AdminBarAsset does not exist
```

Any ideas?

**Comment by wbrowar** [comment]
Hey @neekster, sorry I didn't get to this yet. I'll take a look at it this weekend.

**Comment by nickcobley** [comment]
Awesome, I had uninstalled it thinking the client wasn't using it, they only asked where it was yesterday, perfect timing. Thanks!

**Comment by wbrowar** [comment]
@neekster I couldn't get this error to appear for me, but I removed a place where the plugin was adding in the asset bundle when it shouldn't have. I *think* this is all set, but let me know if you are still seeing the error after upgrading to 3.1.7.

**Comment by nickcobley** [comment]
Thanks for looking into this. I've reinstalled it again with latest version and can confirm the issue is gone for me now.
